### PR TITLE
Proto 4

### PR DESCRIPTION
**Pull request by egregors**
https://github.com/logux/logux/issues/33

### CODE REVIEW

**Comment by ambientlight** [comment]
@ai, @egregors: is there any possible ETA for this?

**Comment by egregors** [comment]
@ambientlight I suppose It would be done during 1-2 weeks. Looks like only subprotocols processing and tests (for backend-test) are left 🐱

**Comment by egregors** [comment]
rel https://github.com/logux/backend-test/issues/6

**Comment by egregors** [comment]
rel https://github.com/logux/backend-test/issues/8

**Pull request merged**
